### PR TITLE
Implemented PLUSARGS for FLI

### LINKED ISSUE #1404: Passing plusargs to FLI: Find code that works with different TCL versions
There is an error on RHEL7 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

Compilation error in ‘Tcl_Interp’ has no member named ‘result’ 

```
 cocotb/share/lib/fli/FliCbHdl.cpp:164:44: error: ‘Tcl_Interp’ has no member named ‘result’
       unsigned long argc_u = strtoul(interp->result, NULL, 10);
                                              ^
  cocotb/share/lib/fli/FliCbHdl.cpp:183:43: error: ‘Tcl_Interp’ has no member named ‘result’
           argv[i] = new char[strlen(interp->result)+1];
                                             ^
  cocotb/share/lib/fli/FliCbHdl.cpp:184:33: error: ‘Tcl_Interp’ has no member named ‘result’
           strcpy(argv[i], interp->result);
                                   ^
```

Seems to be related to https://github.com/cocotb/cocotb/pull/1256  @ktbarrett

### PR DESCRIPTION
**Pull request by ktbarrett**
Fixed version of b283b48368a3a7f507110c6699db3a6c7ce01677. Uses `Tcl_GetStringResult` instead of accessing the internal `result` field, this works on TCL 8.5 and 8.6. Fixes #1404.

Finally got 2019.1 setup and tested this PR against it as well as 10.5c and 10.7c.

I tried using `Tcl_GetVar2Ex` to grab a reference to `argv`, then do processing on it, but there is something weird about how Questa maintains its TCL interpreter because it returns a message that the variable isn't defined. `mti_Cmd` seems to work.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you use `return -level 0 $argv` in place of `GetVar2Ex`, and then extract items from the output of `GetObjResulr`?

**Comment by ktbarrett** [comment]
Don't merge just yet, need to update newsfragment to right PR and add some deallocation.

@eric-wieser That seems like it would work, I'll try it.

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 1]
```diff
@@ -140,6 +144,57 @@ int FliStartupCbHdl::arm_callback()
...
+    if (argc_u > std::numeric_limits<int>::max()) {
+        return;
+    }
+    int argc = static_cast<int>(argc_u);
+    if (argc_u == 0) {
+        return;
+    }
+
+    // allocate storage for argv
+    char** argv = new char*[argc];
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliCbHdl.cpp]: To avoid the appearance leaking, can you declare this a `static vector<std::string>`, and unpack the pointers into the return value?

The value shouldn't change at runtime anyway, so `static` seems appropriate.

Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: It doesn't even need to be `static`, it's no longer used after the call to `gpi_embed_init`, I just wasn't cleaning up afterwards.

Comment (eric-wieser) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: Right, but the design of the GPI doesn't even allow you to clean up, does it? Other implementations return non-owned pointers.

Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: Well it travels up from`gpi_embed_init` to `embed_sim_init`, it gets copied into a Python list and  returns back down the stack. No one holds a reference to it elsewhere. So you could clean up after the call to `gpi_embed_init` in all of the interfaces. You'll see that VHPI cleans up.

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 2]
```diff
@@ -140,6 +144,53 @@ int FliStartupCbHdl::arm_callback()
...
+    }
+    Tcl_Obj* result = Tcl_GetObjResult(interp);
+    Tcl_IncrRefCount(result);
+    Tcl_ResetResult(interp);
+
+    // split TCL list into length and element array
+    int argc;
+    Tcl_Obj** tcl_argv;
+    if ((Tcl_ListObjGetElements(interp, result, &argc, &tcl_argv) != TCL_OK) || (argc == 0)) {
+        const char* errmsg = Tcl_GetStringResult(interp);
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliCbHdl.cpp]: What value will this hold if `argc == 0`?

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 3]
```diff
@@ -166,13 +217,17 @@ int FliStartupCbHdl::run_callback()
...
 
-
-    // copy in sim_info.product
-    sim_info.argc = 0;
-    sim_info.argv = NULL;
     sim_info.product = &product[0];
     sim_info.version = &version[0];
 
+    std::vector<std::string> argv = get_argv();
+    std::vector<char*> argv_cstr;
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliCbHdl.cpp]: I assume we can't make this `char const*`?

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 4]
```diff
@@ -140,6 +144,53 @@ int FliStartupCbHdl::arm_callback()
...
+    int argc;
+    Tcl_Obj** tcl_argv;
+    if ((Tcl_ListObjGetElements(interp, result, &argc, &tcl_argv) != TCL_OK) || (argc == 0)) {
+        const char* errmsg = Tcl_GetStringResult(interp);
+        LOG_WARN("Failed to get argv elements: %s", errmsg);
+        Tcl_DecrRefCount(result);
+        Tcl_ResetResult(interp);
+        return argv;
+    }
+    Tcl_ResetResult(interp);
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliCbHdl.cpp]: Any idea what the result contains here?

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 2 above)
Comment (eric-wieser) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: I think it would be best to split this `if` into two.

File: documentation/source/newsfragments/1424.feature.rst [hunk 5]
```diff
@@ -0,0 +1 @@
+Questa now supports :envvar:`PLUSARGS`. This requires that ``tcl.h`` be present on the system. This is likely included in your installation of Questa. Otherwise, specify ``CXXFLAGS=-I/path/to/tcl/includedir``.
```
Comment (eric-wieser) [inline documentation/source/newsfragments/1424.feature.rst]: Does this `CXXFLAGS` thing still work with the setup.py changes?

Comment (themperek) [reply documentation/source/newsfragments/1424.feature.rst]: Yes. All should work.

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 6]
```diff
@@ -26,6 +26,10 @@
 ******************************************************************************/
 
 #include "FliImpl.h"
+#include "mti.h"
+#undef DLLEXPORT  // redefinition in tcl.h causes warning
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliCbHdl.cpp]: Can you clarify where the original definition came from too?

File: documentation/source/newsfragments/1424.feature.rst (hunk 5 above)
Comment (themperek) [reply documentation/source/newsfragments/1424.feature.rst]: This works so should change `CFLAGS="-I/path_to_mti_h" pip install -v -e .`

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 3 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: sim_info.argv is `char**`, adding const there would require a `const_cast`. But I suppose we should make `sim_info.argv` `const` instead.

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 4 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: Ideally nothing if it succeeds, but I wanted to get the interpreter result back into a clean state before leaving as a matter of cleanliness.

File: documentation/source/newsfragments/1424.feature.rst (hunk 5 above)
Comment (ktbarrett) [reply documentation/source/newsfragments/1424.feature.rst]: The file that includes tcl.h is a C++ file, it's curious that `CFLAGS` works, or is this due to setuptools not supporting `CXXFLAGS` and only using `CFLAGS`?

Comment (themperek) [reply documentation/source/newsfragments/1424.feature.rst]: setuptools seems to support CFLAGS and not CXXFLAG

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 2 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: I think we can remove the second check. `argc == 0` and the function returns `TCL_OK` only when the list is empty, `tcl_argv == NULL`. However, the way this function is written means we will never dereference that `NULL` pointer.

File: documentation/source/newsfragments/1424.feature.rst (hunk 5 above)
Comment (ktbarrett) [reply documentation/source/newsfragments/1424.feature.rst]: Alright, will change.

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 6 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: `gpi.h`, but it isn't used anywhere in the project, so we should probably remove it.

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 3 above)
Comment (eric-wieser) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: Let's leave it as is, this is probably motivated by C's bad handling of indirected const.

File: cocotb/share/lib/fli/FliCbHdl.cpp (hunk 6 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliCbHdl.cpp]: Removed it in a separate commit.
