### PR TITLE
Move to src/ project

### LINKED ISSUE #2286: Move to a src/ layout
The benefits of putting packages in a `src/` directory in Python/pip projects has been discussed for a few years now. The advantages include running coverage collection without doing an editable install and testing what is installed and not what is local. We have to use an editable install in our tox to be able to correctly collect coverage. This has the disadvantage of not being PEP517 compliant in the future (well maybe they will add specifications for editable installs, but I doubt it), and developers have to clean all the build artifacts out every time we run `pip`/`tox` to prevent using potentially out of date C++ libraries which aren't rebuilt if they exist. And editable installs just fundamentally break isolation as provided by tox.

Preliminary testing of a move to a `src/` layout shows that the directory rewriting introduced in #2155 break paths and the build process once we move to a `src/` layout. I'm sure there is some way around this.

### LINKED ISSUE #2698: 'make help' reveals a circular dependency problem in handle.py while importing simulator from cocotb
**Environment:**
* cocotb: 1.5.2
* MinGW32 on Windows 10 64-bit
* GHDL latest MinGW32 installation with mcode backend
* Python 3.9 from MinGW

**Description:**  
After following installation instructions for cocotb (installing gcc, make, pip, ghdl, ...) and then downloading cocotb sources, it gives an error when `make help` is called.
```
Patrick Lehmann@Paebbels-Laptop MINGW32 ~/temp/cocotb
$ make help
Traceback (most recent call last):
  File "C:/msys64/mingw32/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/msys64/mingw32/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/msys64/mingw32/bin/cocotb-config.exe/__main__.py", line 4, in <module>
  File "C:/msys64/home/Patrick Lehmann/temp/cocotb/cocotb/__init__.py", line 43, in <module>
    import cocotb.handle
  File "C:/msys64/home/Patrick Lehmann/temp/cocotb/cocotb/handle.py", line 39, in <module>
    from cocotb import simulator
ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (C:/msys64/home/Patrick Lehmann/temp/cocotb/cocotb/__init__.py)

This cocotb makefile has the following targets

all, test - run regression producing combined_results.xml
            (return error code produced by sub-makes)
jenkins   - run regression producing combined_results.xml
            (return error code 1 if any failure was found)
clean     - remove build directory and all simulation artefacts

The default simulator is Icarus Verilog.
To use another, set the environment variable SIM as below.
Available simulators:

```

I think this circular dependency problem could be checked in CI with a testcase calling `make help` in CI too, right?

### PR DESCRIPTION
**Pull request by ktbarrett**
Reopens #2358 in a new PR. Closes #2286 and closes #2698. Supersedes #3452 and supersedes #3451. This seems to fix the coverage reporting on `cocotb/runner.py`.

All PRs will need to be rebased after this commit. I'm not sure how cleanly that will be done.

### CODE REVIEW

**Review by cmarqu — APPROVED** [review]

**Review by imphil — APPROVED** [review]
Thanks! It's time to get that annoyance out of the way.

Rebases should be fine, git typically handles renames rather well.
